### ISSUE TITLE
voxel-engine fork just isn't rendering anything for me

### ISSUE THREAD

**Issue by sadtaco** [voxel/voxel-mesher#10]
It  won't let me post an issue at https://github.com/deathcap/voxel-engine so I thought I'd open one here.

If I try a simple example like...
package.json:

    {
      "name": "voxels",
      "version": "0.0.1",
      "description": "literally nothing",
      "scripts": {
        "start": "beefy game.js:build.js 8080"
      },
      "devDependencies": {
        "beefy": "^2.1.1",
        "voxel-engine": "maxogden/voxel-engine#82023105dab9eccb3aab1c6e81431cf239be4473"
      }
    }

index.js:

    var createGame = require('voxel-engine');
    var game = createGame();
    game.appendTo(document.body);

All I see is the light blue sky.  I don't see any voxels.  It's my understanding it should generate a sphere by default. I also tried different inputs in generate:

I also tried the "materialParams: { color: 0xffffff, wireframe: true, transparent: true, opacity: 0.5, side: THREE.DoubleSide }" option in case there was something with the material not making them render, which is what I figured was the problem.

How do I do a basic, working, hello-world sort of example with your fork?

**Comment by deathcap** [comment]
hey @sadtaco , sorry for the neglect, but to answer your questions if you're still interested or if anyone else sees the same issues in the future:

https://github.com/deathcap/voxel-engine (ndarray branch), also formerly https://github.com/maxogden/voxel-engine/tree/ndarray - is now available and published separately as https://github.com/voxel/voxel-engine-stackgl and issues can be opened there (no doubt there are many more)

> It's my understanding it should generate a sphere by default. I also tried different inputs in generate:

There are two basic strategies for chunk generation: in the `generate()` function with the `generateChunks: true` option, or listening for `missingChunk` events with `generateChunks: false`. The latter is used by https://github.com/voxel/voxel-land and is more flexible; generateChunks true might not be working as expected or completely ported over. 

> I also tried the "materialParams: { color: 0xffffff, wireframe: true, transparent: true, opacity: 0.5, side: THREE.DoubleSide }" option in case there was something with the material not making them render, which is what I figured was the problem.

materials, materialParams, materialType, materialParams are no longer used in voxel-engine-stackgl (to do: document in https://github.com/voxel/voxel-engine-stackgl/issues/2), those are vestiges from the three.js-based version, as is THREE.DoubleSide (no `THREE.*` symbols are available, voxel-engine-stackgl has completely converted to using https://github.com/stackgl Modular WebGL components instead of https://github.com/mrdoob/three.js). Instead, material textures are handled by https://github.com/voxel/voxel-shader and https://github.com/voxel/voxel-mesher. Wireframe is available in an optional separate shader plugin: https://github.com/voxel/voxel-wireframe

> How do I do a basic, working, hello-world sort of example with your fork?

Here is the voxel-engine-stackgl example (comparable to voxel-hello-world, but for the stackgl/ndarray fork instead of three.js): https://github.com/deathcap/voxel-example/ (unfortunately, it is currently broken at the time of this writing, but watch https://github.com/deathcap/voxel-example/issues/4)
